In [1]:
import pandas as pd
import requests
from config import api_key, email

In [7]:
# API endpoint with your credentials
url = f"https://aqs.epa.gov/data/api/annualData/byState?email={email}&key={api_key}&param=44201&bdate=20210101&edate=20211231&state=06"

# Send the request to the API
response = requests.get(url)

In [8]:
# Check if the request was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Load data into a Pandas DataFrame
    df = pd.json_normalize(data['Data'])
    print(df.head())
else:
    print(f"Error: {response.status_code}")

  state_code county_code site_number parameter_code  poc   latitude  \
0         06         073        1006          44201    1  32.842318
1         06         073        1006          44201    1  32.842318
2         06         073        1006          44201    1  32.842318
3         06         073        1006          44201    1  32.842318
4         06         059        0007          44201    1  33.830620

    longitude  datum parameter sample_duration_code  ... fiftieth_percentile  \
0 -116.768293  NAD83     Ozone                    1  ...               0.060
1 -116.768293  NAD83     Ozone                    W  ...               0.053
2 -116.768293  NAD83     Ozone                    W  ...               0.053
3 -116.768293  NAD83     Ozone                    W  ...               0.053
4 -117.938450  WGS84     Ozone                    1  ...               0.045

  tenth_percentile local_site_name               site_address       state  \
0            0.046          Alpine  2300 VICTORIA DR., ALPINE  California
1            0.043          Alpine  2300 VICTORIA DR., ALPINE  California
2            0.043          Alpine  2300 VICTORIA DR., ALPINE  California
3            0.043          Alpine  2300 VICTORIA DR., ALPINE  California
4            0.033         Anaheim        1630 W. PAMPAS LANE  California

      county     city  cbsa_code                                cbsa  \
0  San Diego   Alpine      41740              San Diego-Carlsbad, CA
1  San Diego   Alpine      41740              San Diego-Carlsbad, CA
2  San Diego   Alpine      41740              San Diego-Carlsbad, CA
3  San Diego   Alpine      41740              San Diego-Carlsbad, CA
4     Orange  Anaheim      31080  Los Angeles-Long Beach-Anaheim, CA

  date_of_last_change
0          2024-05-26
1          2024-05-26
2          2024-05-26
3          2024-05-26
4          2024-05-26

[5 rows x 56 columns]

In [9]:
df

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,...,fiftieth_percentile,tenth_percentile,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,06,073,1006,44201,1,32.842318,-116.768293,NAD83,Ozone,1,...,0.060,0.046,Alpine,"2300 VICTORIA DR., ALPINE",California,San Diego,Alpine,41740,"San Diego-Carlsbad, CA",2024-05-26
1,06,073,1006,44201,1,32.842318,-116.768293,NAD83,Ozone,W,...,0.053,0.043,Alpine,"2300 VICTORIA DR., ALPINE",California,San Diego,Alpine,41740,"San Diego-Carlsbad, CA",2024-05-26
2,06,073,1006,44201,1,32.842318,-116.768293,NAD83,Ozone,W,...,0.053,0.043,Alpine,"2300 VICTORIA DR., ALPINE",California,San Diego,Alpine,41740,"San Diego-Carlsbad, CA",2024-05-26
3,06,073,1006,44201,1,32.842318,-116.768293,NAD83,Ozone,W,...,0.053,0.043,Alpine,"2300 VICTORIA DR., ALPINE",California,San Diego,Alpine,41740,"San Diego-Carlsbad, CA",2024-05-26
4,06,059,0007,44201,1,33.830620,-117.938450,WGS84,Ozone,1,...,0.045,0.033,Anaheim,1630 W. PAMPAS LANE,California,Orange,Anaheim,31080,"Los Angeles-Long Beach-Anaheim, CA",2024-05-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,06,025,4004,44201,1,33.213611,-115.545280,WGS84,Ozone,W,...,0.029,0.015,Niland-English Road,"7711 ENGLISH ROAD, NILAND",California,Imperial,None,20940,"El Centro, CA",2024-05-26
732,06,069,0003,44201,1,36.483240,-121.156880,WGS84,Ozone,1,...,0.046,0.036,Pinnacles NP - Southwest of East Entrance Station,"Northeast entrance, Pinnacles National Park",California,San Benito,None,41940,"San Jose-Sunnyvale-Santa Clara, CA",2024-05-26
733,06,069,0003,44201,1,36.483240,-121.156880,WGS84,Ozone,W,...,0.043,0.033,Pinnacles NP - Southwest of East Entrance Station,"Northeast entrance, Pinnacles National Park",California,San Benito,None,41940,"San Jose-Sunnyvale-Santa Clara, CA",2024-05-26
734,06,069,0003,44201,1,36.483240,-121.156880,WGS84,Ozone,W,...,0.043,0.033,Pinnacles NP - Southwest of East Entrance Station,"Northeast entrance, Pinnacles National Park",California,San Benito,None,41940,"San Jose-Sunnyvale-Santa Clara, CA",2024-05-26
735,06,069,0003,44201,1,36.483240,-121.156880,WGS84,Ozone,W,...,0.043,0.033,Pinnacles NP - Southwest of East Entrance Station,"Northeast entrance, Pinnacles National Park",California,San Benito,None,41940,"San Jose-Sunnyvale-Santa Clara, CA",2024-05-26

In [10]:
unique_counts = df.nunique()
print(unique_counts)

state_code                       1
county_code                     49
site_number                     80
parameter_code                   1
poc                              2
latitude                       172
longitude                      172
datum                            2
parameter                        1
sample_duration_code             2
sample_duration                  2
pollutant_standard               4
metric_used                      3
method                           5
year                             1
units_of_measure                 1
event_type                       4
observation_count              446
observation_percent             42
validity_indicator               2
valid_day_count                 98
required_day_count               2
exceptional_data_count          14
null_observation_count         159
primary_exceedance_count        64
secondary_exceedance_count      64
certification_indicator          3
arithmetic_mean                541
standard_deviation             529
first_max_value                 84
first_max_datetime             220
second_max_value                85
second_max_datetime            233
third_max_value                 80
third_max_datetime             265
fourth_max_value                81
fourth_max_datetime            276
first_max_nonoverlap_value       0
first_max_n_o_datetime           0
second_max_nonoverlap_value      0
second_max_n_o_datetime          0
ninety_ninth_percentile         80
ninety_eighth_percentile        78
ninety_fifth_percentile         73
ninetieth_percentile            67
seventy_fifth_percentile        57
fiftieth_percentile             42
tenth_percentile                37
local_site_name                172
site_address                   172
state                            1
county                          49
city                           127
cbsa_code                       33
cbsa                            33
date_of_last_change              4
dtype: int64

In [11]:
df.to_csv("filename-annual-2021.csv", index=False)

In [12]:
# API endpoint with your credentials
url1 = f"https://aqs.epa.gov/data/api/annualData/byState?email={email}&key={api_key}&param=42101&bdate=20210101&edate=20211231&state=06"

# Send the request to the API
response = requests.get(url1)

In [13]:
# Check if the request was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Load data into a Pandas DataFrame
    df = pd.json_normalize(data['Data'])
    print(df.head())
else:
    print(f"Error: {response.status_code}")

  state_code county_code site_number parameter_code  poc   latitude  \
0         06         059        0007          42101    1  33.830620
1         06         059        0007          42101    1  33.830620
2         06         059        0008          42101    1  33.819305
3         06         059        0008          42101    1  33.819305
4         06         067        0006          42101    1  38.613779

    longitude  datum        parameter sample_duration_code  ...  \
0 -117.938450  WGS84  Carbon monoxide                    1  ...
1 -117.938450  WGS84  Carbon monoxide                    Z  ...
2 -117.918759  WGS84  Carbon monoxide                    1  ...
3 -117.918759  WGS84  Carbon monoxide                    Z  ...
4 -121.368014  WGS84  Carbon monoxide                    1  ...

  fiftieth_percentile tenth_percentile            local_site_name  \
0               0.200            0.100                    Anaheim
1               0.200            0.100                    Anaheim
2               0.642            0.406          Anaheim Near-Road
3               0.600            0.500          Anaheim Near-Road
4               0.154            0.110  Sacramento-Del Paso Manor

                            site_address       state      county  \
0                    1630 W. PAMPAS LANE  California      Orange
1                    1630 W. PAMPAS LANE  California      Orange
2  812 W. Vermont St., Anaheim, CA 92802  California      Orange
3  812 W. Vermont St., Anaheim, CA 92802  California      Orange
4    DEL PASO-2701 AVALON DR, SACRAMENTO  California  Sacramento

           city  cbsa_code                                     cbsa  \
0       Anaheim      31080       Los Angeles-Long Beach-Anaheim, CA
1       Anaheim      31080       Los Angeles-Long Beach-Anaheim, CA
2       Anaheim      31080       Los Angeles-Long Beach-Anaheim, CA
3       Anaheim      31080       Los Angeles-Long Beach-Anaheim, CA
4  Arden-Arcade      40900  Sacramento--Roseville--Arden-Arcade, CA

  date_of_last_change
0          2022-03-15
1          2022-03-15
2          2022-03-15
3          2022-03-15
4          2024-11-06

[5 rows x 56 columns]

In [14]:
df.to_csv("filename-annual-mon-2021.csv", index=False)

In [15]:
# API endpoint with your credentials
url1 = f"https://aqs.epa.gov/data/api/annualData/byState?email={email}&key={api_key}&param=42602&bdate=20210101&edate=20211231&state=06"

# Send the request to the API
response = requests.get(url1)

# Check if the request was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Load data into a Pandas DataFrame
    df = pd.json_normalize(data['Data'])
    print(df.head())
else:
    print(f"Error: {response.status_code}")

df.to_csv("filename-annual-mon-2021.csv", index=False)

  state_code county_code site_number parameter_code  poc   latitude  \
0         06         073        1006          42602    1  32.842318
1         06         073        1006          42602    1  32.842318
2         06         073        1006          42602    2  32.842318
3         06         073        1006          42602    2  32.842318
4         06         059        0007          42602    5  33.830620

    longitude  datum               parameter sample_duration_code  ...  \
0 -116.768293  NAD83  Nitrogen dioxide (NO2)                    1  ...
1 -116.768293  NAD83  Nitrogen dioxide (NO2)                    1  ...
2 -116.768293  NAD83  Nitrogen dioxide (NO2)                    1  ...
3 -116.768293  NAD83  Nitrogen dioxide (NO2)                    1  ...
4 -117.938450  WGS84  Nitrogen dioxide (NO2)                    1  ...

  fiftieth_percentile tenth_percentile local_site_name  \
0                 4.0              1.0          Alpine
1                 9.0              4.0          Alpine
2                 2.0              0.0          Alpine
3                 8.0              2.0          Alpine
4                 8.3              2.6         Anaheim

                site_address       state     county     city  cbsa_code  \
0  2300 VICTORIA DR., ALPINE  California  San Diego   Alpine      41740
1  2300 VICTORIA DR., ALPINE  California  San Diego   Alpine      41740
2  2300 VICTORIA DR., ALPINE  California  San Diego   Alpine      41740
3  2300 VICTORIA DR., ALPINE  California  San Diego   Alpine      41740
4        1630 W. PAMPAS LANE  California     Orange  Anaheim      31080

                                 cbsa date_of_last_change
0              San Diego-Carlsbad, CA          2024-05-22
1              San Diego-Carlsbad, CA          2024-05-22
2              San Diego-Carlsbad, CA          2024-05-22
3              San Diego-Carlsbad, CA          2024-05-22
4  Los Angeles-Long Beach-Anaheim, CA          2024-05-22

[5 rows x 56 columns]